jay-tech:
  application:
    security:
      # In milliseconds (1 Hour)
      access-token-expiry-date: 3600000
      # In milliseconds (180 Days)
      refresh-token-expiry-date: 15552000000

logging:
  level:
    org:
      springframework: debug

spring:
  profiles:
    active: development
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect