jay-tech:
  application:
    security:
      # In milliseconds (1 Hour)
      access-token-expiry-date: 3600000
      # In milliseconds (180 Days)
      refresh-token-expiry-date: 15552000000

spring:
  profiles:
    active: development
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoint:
    beans:
      cache:
        time-to-live: "10s"
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
#        http://localhost:7465/development/actuator

